Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -85,6 +85,18 @@ jobs:
           fi
           echo "VERSION=$VERSION" >> $GITHUB_ENV
 
+      - name: Build Application
+        run: |
+          # Ensure dependencies are installed
+          npm install
+          # Build the application to generate the 'build' directory
+          npm run build
+          # Verify the 'build' directory exists
+          if [ ! -d "app/build" ]; then
+            echo "Error: 'app/build' directory not found after build step."
+            exit 1
+          fi
+          
       - name: Build and push Docker image
         uses: docker/build-push-action@v2
         with:
